chore(deps): update dependency aws-cdk-lib to v2.118.0 (#202)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [aws-cdk-lib](https://togithub.com/aws/aws-cdk)
([source](https://togithub.com/aws/aws-cdk/tree/HEAD/packages/aws-cdk-lib))
| [`2.116.0` ->
`2.118.0`](https://renovatebot.com/diffs/npm/aws-cdk-lib/2.116.0/2.118.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/aws-cdk-lib/2.118.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/aws-cdk-lib/2.118.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/aws-cdk-lib/2.116.0/2.118.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/aws-cdk-lib/2.116.0/2.118.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

@coderabbitai: ignore

---

### Release Notes

<details>
<summary>aws/aws-cdk (aws-cdk-lib)</summary>

### [`v2.118.0`](https://togithub.com/aws/aws-cdk/releases/tag/v2.118.0)

[Compare
Source](https://togithub.com/aws/aws-cdk/compare/v2.117.0...v2.118.0)

##### Features

- **appsync:** IntrospectionConfig property
([#&#8203;28500](https://togithub.com/aws/aws-cdk/issues/28500))
([98ed6b3](https://togithub.com/aws/aws-cdk/commit/98ed6b3346e4afd423592296bb1620d20544acad)),
closes [#&#8203;28429](https://togithub.com/aws/aws-cdk/issues/28429)
- **autoscaling:** add support for `InstanceRequirements` property
([#&#8203;28464](https://togithub.com/aws/aws-cdk/issues/28464))
([276e3a6](https://togithub.com/aws/aws-cdk/commit/276e3a66febf32afc65a93d7296ec6be8f6e2126)),
closes [#&#8203;28393](https://togithub.com/aws/aws-cdk/issues/28393)
- **cloudfront:** CloudFront Function runtime property
([#&#8203;28099](https://togithub.com/aws/aws-cdk/issues/28099))
([9b466ae](https://togithub.com/aws/aws-cdk/commit/9b466ae136910d07d4297a31f1010fa26ce864d0)),
closes [#&#8203;28163](https://togithub.com/aws/aws-cdk/issues/28163)
- **cloudfront:** Key Value Store L2
([#&#8203;28473](https://togithub.com/aws/aws-cdk/issues/28473))
([030db42](https://togithub.com/aws/aws-cdk/commit/030db42ad06a471af3833665cb80dceee034aa02)),
closes [#&#8203;28377](https://togithub.com/aws/aws-cdk/issues/28377)
- **codepipeline-actions:** more convenient methods to `CacheControl`
([#&#8203;28491](https://togithub.com/aws/aws-cdk/issues/28491))
([a59dc0c](https://togithub.com/aws/aws-cdk/commit/a59dc0cb79af98ee601f352a7cf1b5fa9cc4d365)),
closes [#&#8203;25477](https://togithub.com/aws/aws-cdk/issues/25477)
- **ecs:** `interactive` option in `ContainerDefinitionOptions`
([#&#8203;28536](https://togithub.com/aws/aws-cdk/issues/28536))
([1f9788f](https://togithub.com/aws/aws-cdk/commit/1f9788f8ad45c0f159c9b7e6bafb76763e9b0bea)),
closes [#&#8203;24326](https://togithub.com/aws/aws-cdk/issues/24326)
- **ecs:** enable cluster to grant task protection API permissions to
IAM entities
([#&#8203;28486](https://togithub.com/aws/aws-cdk/issues/28486))
([9bc972b](https://togithub.com/aws/aws-cdk/commit/9bc972b923b66248fb8392e9cba1b2b5829c6e1b)),
closes [#&#8203;26233](https://togithub.com/aws/aws-cdk/issues/26233)
- **ecs:** nvidia support to BottlerocketEcsVariant enum for
gpu-accelerated tasks
([#&#8203;28488](https://togithub.com/aws/aws-cdk/issues/28488))
([832e29a](https://togithub.com/aws/aws-cdk/commit/832e29a47c2cb67558c0148a3bf1fa22e4d5cb82)),
closes [#&#8203;25980](https://togithub.com/aws/aws-cdk/issues/25980)
- **iam:** validate roleName
([#&#8203;28509](https://togithub.com/aws/aws-cdk/issues/28509))
([999c01a](https://togithub.com/aws/aws-cdk/commit/999c01a1250308b482fe33e651d7ee8da1f96956)),
closes [#&#8203;28502](https://togithub.com/aws/aws-cdk/issues/28502)
- **opensearchservice:** ip address type for domain
([#&#8203;28497](https://togithub.com/aws/aws-cdk/issues/28497))
([6b80338](https://togithub.com/aws/aws-cdk/commit/6b80338be59bdfa1d14d81fa1ae79f2eda889b37)),
closes [#&#8203;28436](https://togithub.com/aws/aws-cdk/issues/28436)
- **rds:** `timeout` and `timeoutAction` properties to ServerlessCluster
([#&#8203;28534](https://togithub.com/aws/aws-cdk/issues/28534))
([508825b](https://togithub.com/aws/aws-cdk/commit/508825b14d6ccae7274afc08487329162182e887)),
closes [#&#8203;27183](https://togithub.com/aws/aws-cdk/issues/27183)
- **rds:** ClientPasswordAuthType property on DatabaseProxy
([#&#8203;28540](https://togithub.com/aws/aws-cdk/issues/28540))
([669e6ff](https://togithub.com/aws/aws-cdk/commit/669e6ffc6e9d8c7b06cb0f62348635f933b6f823)),
closes [#&#8203;28415](https://togithub.com/aws/aws-cdk/issues/28415)
- **rds:** new Aurora Postgres engine versions
([#&#8203;28508](https://togithub.com/aws/aws-cdk/issues/28508))
([9d8b06f](https://togithub.com/aws/aws-cdk/commit/9d8b06f6478a98e01e3aaa86c1dbf22d6e861f05))
- **stepfunctions-tasks:** add `timeout` parameter for EmrCreateCluster
([#&#8203;28532](https://togithub.com/aws/aws-cdk/issues/28532))
([ca91626](https://togithub.com/aws/aws-cdk/commit/ca91626327ac4a138adc16026d951f21fadf86a3)),
closes
[/github.com/aws/aws-cdk/pull/28529#discussion_r1438587964](https://togithub.com/aws//github.com/aws/aws-cdk/pull/28529/issues/discussion_r1438587964)
- **stepfunctions-tasks:** add validations for EmrCreateCluster
([#&#8203;28529](https://togithub.com/aws/aws-cdk/issues/28529))
([e0b725c](https://togithub.com/aws/aws-cdk/commit/e0b725cd39a01a8387dcf28921e0912552eb7fce))
- **stepfunctions-tasks:** additional allocation strategies for spot
instance fleets in EmrCreateCluster
([#&#8203;28525](https://togithub.com/aws/aws-cdk/issues/28525))
([94003ec](https://togithub.com/aws/aws-cdk/commit/94003ecb056e56623aa6621a2d013c1a7e3dcebe))

##### Bug Fixes

- **cli:** direct deploy method fails when there are no updates
([#&#8203;28523](https://togithub.com/aws/aws-cdk/issues/28523))
([dde5975](https://togithub.com/aws/aws-cdk/commit/dde59755cb71aee73a58f3b2c2068f2ae01e9b72)),
closes
[/github.com/aws/aws-cdk/blob/9d8b06f6478a98e01e3aaa86c1dbf22d6e861f05/packages/aws-cdk/lib/api/util/cloudformation.ts#L290-L296](https://togithub.com/aws//github.com/aws/aws-cdk/blob/9d8b06f6478a98e01e3aaa86c1dbf22d6e861f05/packages/aws-cdk/lib/api/util/cloudformation.ts/issues/L290-L296)
- **events:** event bus fails with duplicate policy resource
([#&#8203;28521](https://togithub.com/aws/aws-cdk/issues/28521))
([166967f](https://togithub.com/aws/aws-cdk/commit/166967f11727a28fc11b9af5de0fad6da2a4ad64)),
closes [#&#8203;27340](https://togithub.com/aws/aws-cdk/issues/27340)
[#&#8203;28520](https://togithub.com/aws/aws-cdk/issues/28520)
- **iam:** withConditions overrides Principal actions
([#&#8203;28510](https://togithub.com/aws/aws-cdk/issues/28510))
([0b345c5](https://togithub.com/aws/aws-cdk/commit/0b345c5a98a61ae7a587e5578ffdfc69885bb676)),
closes [#&#8203;28426](https://togithub.com/aws/aws-cdk/issues/28426)
- **rds:** circular dependencies when creating multiple DatabaseProxies
([#&#8203;28471](https://togithub.com/aws/aws-cdk/issues/28471))
([a12d9eb](https://togithub.com/aws/aws-cdk/commit/a12d9eb75cc110657a73c6cb82399d572696d36e)),
closes
[/github.com/aws/aws-cdk/blob/cd54c4239ec29182e30fd91634505df560d6e5f8/packages/aws-cdk-lib/aws-rds/lib/cluster.ts#L446](https://togithub.com/aws//github.com/aws/aws-cdk/blob/cd54c4239ec29182e30fd91634505df560d6e5f8/packages/aws-cdk-lib/aws-rds/lib/cluster.ts/issues/L446)
[#&#8203;25633](https://togithub.com/aws/aws-cdk/issues/25633)

***

#### Alpha modules (2.118.0-alpha.0)

##### Features

- **glue:** database description property
([#&#8203;27744](https://togithub.com/aws/aws-cdk/issues/27744))
([cbac240](https://togithub.com/aws/aws-cdk/commit/cbac24041db7dbc39b4ae1d6da4902b3443528cb)),
closes [#&#8203;27740](https://togithub.com/aws/aws-cdk/issues/27740)
- **glue-alpha:** add `cfn-glue-table-tableinput-parameters` to Glue
table construct
([#&#8203;27643](https://togithub.com/aws/aws-cdk/issues/27643))
([8e15482](https://togithub.com/aws/aws-cdk/commit/8e15482295c1324eefea020faeb11e4c686357c6))

##### Bug Fixes

- **lambda-go:** path with space breaks go build
([#&#8203;28554](https://togithub.com/aws/aws-cdk/issues/28554))
([a8a639e](https://togithub.com/aws/aws-cdk/commit/a8a639e2a2114162db240361c32c40a596a7a19e)),
closes [#&#8203;28555](https://togithub.com/aws/aws-cdk/issues/28555)

### [`v2.117.0`](https://togithub.com/aws/aws-cdk/releases/tag/v2.117.0)

[Compare
Source](https://togithub.com/aws/aws-cdk/compare/v2.116.1...v2.117.0)

##### Features

- update L1 CloudFormation resource definitions
([#&#8203;28489](https://togithub.com/aws/aws-cdk/issues/28489))
([607dccb](https://togithub.com/aws/aws-cdk/commit/607dccb0fd920d25f0fe2613b83c9830322c439e)),
closes
[/docs.aws.amazon.com/datasync/latest/userguide/working-with-locations.html#create-s3](https://togithub.com/aws//docs.aws.amazon.com/datasync/latest/userguide/working-with-locations.html/issues/create-s3)
- **api-gateway-v2:** Add method to generate flexible execute-api ARN
([#&#8203;28400](https://togithub.com/aws/aws-cdk/issues/28400))
([0932027](https://togithub.com/aws/aws-cdk/commit/09320276c2c08ace1d85b970fe91bc1bea208457)),
closes [#&#8203;23301](https://togithub.com/aws/aws-cdk/issues/23301)
- **autoscaling:** instance maintenance policy for AutoScalingGroup
([#&#8203;28092](https://togithub.com/aws/aws-cdk/issues/28092))
([5eb2c26](https://togithub.com/aws/aws-cdk/commit/5eb2c262141d197073173037fc350c26920b774f)),
closes [#&#8203;28042](https://togithub.com/aws/aws-cdk/issues/28042)
- **codebuild:** Lambda compute for codebuild projects
([#&#8203;27934](https://togithub.com/aws/aws-cdk/issues/27934))
([a4a4c6f](https://togithub.com/aws/aws-cdk/commit/a4a4c6f19719b9238e2f397d0049af867846ad94)),
closes [#&#8203;28418](https://togithub.com/aws/aws-cdk/issues/28418)
- **core:** option to disable cache for docker build
([#&#8203;27944](https://togithub.com/aws/aws-cdk/issues/27944))
([84d81b6](https://togithub.com/aws/aws-cdk/commit/84d81b67ee2574c98c4a26d8b5c567be84b6cf02)),
closes [#&#8203;27916](https://togithub.com/aws/aws-cdk/issues/27916)
- **ec2:** trn1 instance type
([#&#8203;28477](https://togithub.com/aws/aws-cdk/issues/28477))
([ed02d5c](https://togithub.com/aws/aws-cdk/commit/ed02d5c148a9412e92ee62d35560526b14cfc907))
- **ecs:** Implement method in ECS cluster to retrieve task ARN
([#&#8203;28381](https://togithub.com/aws/aws-cdk/issues/28381))
([7635bbc](https://togithub.com/aws/aws-cdk/commit/7635bbc9b4d766a7920747dd73c571bee90895f9)),
closes [#&#8203;26232](https://togithub.com/aws/aws-cdk/issues/26232)
- **ecs-patterns:** support disabling CPU-based scaling and custom
target utilization
([#&#8203;28315](https://togithub.com/aws/aws-cdk/issues/28315))
([3cb3e02](https://togithub.com/aws/aws-cdk/commit/3cb3e0299ee427a02161a4e5bb250dad8ab3909a)),
closes [#&#8203;20706](https://togithub.com/aws/aws-cdk/issues/20706)
[#&#8203;20706](https://togithub.com/aws/aws-cdk/issues/20706)
- **elasticloadbalancingv2:** dualstack NetworkLoadBalancer
([#&#8203;27546](https://togithub.com/aws/aws-cdk/issues/27546))
([e03a41f](https://togithub.com/aws/aws-cdk/commit/e03a41f5cbafda74a193cd64955674e59a654a78)),
closes
[/docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2](https://togithub.com/aws//docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html/issues/cfn-elasticloadbalancingv2)
[#&#8203;27538](https://togithub.com/aws/aws-cdk/issues/27538)
- **elasticloadbalancingv2:** FIPS compliant SSL policy to ALB
([#&#8203;28479](https://togithub.com/aws/aws-cdk/issues/28479))
([7bb72e1](https://togithub.com/aws/aws-cdk/commit/7bb72e1e1bcc84f45ebe714e379fa085a5642355)),
closes [#&#8203;28455](https://togithub.com/aws/aws-cdk/issues/28455)
- **globalaccelerator:** add support for ip addresses and type
([#&#8203;28055](https://togithub.com/aws/aws-cdk/issues/28055))
([943abe8](https://togithub.com/aws/aws-cdk/commit/943abe877cfbcbb54311e2ecc4a9a3bfb231a202)),
closes [#&#8203;28051](https://togithub.com/aws/aws-cdk/issues/28051)
[#&#8203;28209](https://togithub.com/aws/aws-cdk/issues/28209)
- **ses:** synth-time naming validation for dedicatedIpPoolName
([#&#8203;28466](https://togithub.com/aws/aws-cdk/issues/28466))
([be6ddb8](https://togithub.com/aws/aws-cdk/commit/be6ddb88cce057ef23ff8fee67a4f5b3f063a931)),
closes [#&#8203;28451](https://togithub.com/aws/aws-cdk/issues/28451)

##### Bug Fixes

- **core:** core constructs fail with `Error: Cannot find module
'../dist/core/<file>.generated'`
([#&#8203;28467](https://togithub.com/aws/aws-cdk/issues/28467))
([cd54c42](https://togithub.com/aws/aws-cdk/commit/cd54c4239ec29182e30fd91634505df560d6e5f8)),
closes [#&#8203;28251](https://togithub.com/aws/aws-cdk/issues/28251)
[#&#8203;28465](https://togithub.com/aws/aws-cdk/issues/28465)
- **ecs-patterns:** `ApplicationMultipleTargetGroupsEc2Service` ignores
load balancer name
([#&#8203;28394](https://togithub.com/aws/aws-cdk/issues/28394))
([9c0fecf](https://togithub.com/aws/aws-cdk/commit/9c0fecf9a5cc26416e814ae4754729b54c827b9d)),
closes [#&#8203;23535](https://togithub.com/aws/aws-cdk/issues/23535)

***

#### Alpha modules (2.117.0-alpha.0)

##### Bug Fixes

- **lambda-python-alpha:** bundling hash logic includes auth tokens in
PIP urls, causing an unnecessary rebuild
([#&#8203;27903](https://togithub.com/aws/aws-cdk/issues/27903))
([00331a7](https://togithub.com/aws/aws-cdk/commit/00331a7292a3e60ea5ba3caf2a4fd4cca2fe7dc5)),
closes [#&#8203;27331](https://togithub.com/aws/aws-cdk/issues/27331)
- **lambda-python-alpha:** use function architecture
([#&#8203;18696](https://togithub.com/aws/aws-cdk/issues/18696))
([#&#8203;28449](https://togithub.com/aws/aws-cdk/issues/28449))
([c724d27](https://togithub.com/aws/aws-cdk/commit/c724d277277c45b421dcd89ee1a6d4b54f942d3b))

### [`v2.116.1`](https://togithub.com/aws/aws-cdk/releases/tag/v2.116.1)

[Compare
Source](https://togithub.com/aws/aws-cdk/compare/v2.116.0...v2.116.1)

##### Bug Fixes

- **core:** core constructs fail with `Error: Cannot find module
'../dist/core/<file>.generated'`
([#&#8203;28467](https://togithub.com/aws/aws-cdk/issues/28467))
([e8be128](https://togithub.com/aws/aws-cdk/commit/e8be12836cdb73b74cd36e19e5cec52258304933)),
closes [#&#8203;28251](https://togithub.com/aws/aws-cdk/issues/28251)
[#&#8203;28465](https://togithub.com/aws/aws-cdk/issues/28465)

***

##### Alpha modules (2.116.1-alpha.0)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/cuculus-dev/cuculus).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4xMDMuMSIsInVwZGF0ZWRJblZlciI6IjM3LjEwMy4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>